---
title: "README"
output: github_document
---
# Dallin Annotations
In this folder, I will keep all of my .rmd documents. Some of them will be created by me, but most will take Adriel's code in other folders and annotate it. I hope that by doing so, I will better understand his code, and be able to contribute more to writing the paper on our reasearch. Additionally, I hope these annotations help future RA's understand the code as well.

The numbering of the files is an attempt to be consistent with the tidyverse style guide section 1.1 (found at https://style.tidyverse.org/). As I work more with the code, I will do my best to ensure that the numbering reflects a logical flow for the code. 

If the documents only contain a single, massive block of code, this means that I haven't gotten around to annotating that script.

Below, I have a quick and brief documentation of what I understand about each file. 

# Overview of Files
Note: Files prefaced by 99_ are files that I don't understand completely, and seem to be more related to data wrangling than model building. 

### 01_test_rds_connection.R
This file contains the credentials necessary to log into the R Data Server. It also has brief code for extracting some of the tweets from the database, and it writes the data to a .txt file. 

### 02_visualize_twitter_data.R
This file takes airline twitter data and creates a few visualizations (i.e. wordclouds) on the tweet text. It was formerly called CountingCockroaches.R.

### 03_analyze_complaint_categories.Rmd
This file analyzes our train/test dataset, documents the label types, visualizes the number of complaints to non-complaints, and visualizes the number of each complaint category. Additionally, it runs a tf_idf analysis on the catch-all complaint category to see if another category can be identified. 

### 04_build_fasttext_supervised_classifier.Rmd
This file documents the building of our fastText supervised classifier model.

### 05_define_culstering_functions.R
This file was formerly called clus_func.R. It contains the code defining a few functions. These functions will be referenced in future scripts to help build our model. One especially important function here is the avg_word_vec function. 

##### Average Word Vector Function
This function will take the word vectors for each word in a tweet, and will average the vectors to create a single vector representing the tweet as a whole. The word vectors will be generated by a fasttext unsupervised model. This will effectively become a mathmatical summary of each tweet, and will be a valuable input to our model.

### 06_define_prediction_functions.R
This file was formerly called predict_func.R. It contains a lot of useful functions for our model. Two important functions defined here are the VectorizeTweet() and TweetFeatures() functions.

##### VectorizeTweet Function.
This function has two classes: one for use with a unsupervised fastText model, and another for use with a PCA model trained on the output of the VectorizeTweet() function. This class is functionally identical to the avg_word_vec() function (as far as I understand--looking at the code they should do the exact same thing, so I'm not entirely sure why we have two nearly identical functions).

The first class (used with an unsupervised fastText model) breaks a tweet down into individual words, and finds the word vectors associated with each of these words. After these word vectors are stored in a dataframe, each variable of the dataframe is averaged to produce a single vector (the same size as an individual word vector). This "tweet vector" can be thought of as a mathematical summary of the tweet. 

The second class (used with a PCA model trained on the output of the first class), produces a tibble with the first n principal components of the tweet vector (where n is defined by the user).

##### TweetFeatures Function
This function creates a simple summary of a tweet's features (i.e. the number of exclamation points, the number of links used, and the number of times this user has been mentioned previously in the data).

### 07_build_classifier.Rmd
This document was formerly called classifier_construction.R. It contains the code that builds models referenced in other files, namely the model50-tweet_sample_2M_noRT.dat and xgb.modelPC4-xgb_version.dat. The xgb.modelPC4-xgb_version.dat model is the full, frankenstein model we have built. When I reference "the model," or the "frankenstein model," this is the model I am referring to.

Note: I can't seem to find the logit_classifier_func.R file anywhere. It's referenced in classifier_construction.R

### 08_define_tweet_complaint_predictor_function.R
tweet_complaint_predictor.Rmd builds a function named newTweetComplaintPredictor, which is referenced in serveral other scripts. This function uses our model to predict

### 09_classifier_testing.Rmd
This file references the full model, and makes predictions on single tweets. You can use it to see how the model will react with tweets you find online, as well as tweets you write yourself. 

### 99_batch_classification.Rmd
### 99_build_standalone_fasttext_classification_model.Rmd
In this file, I create my own fastText supervised classification model to see how well it can classify on its own (i.e. without the help of a PCA and XGBoost model). This will be a good base to compare against our own xgboost model built in 07_construct_classifier.Rmd

Note: Code still has a few places it needs to be tweaked and isn't fully funcitonal yet--I need to write the .txt files and figure out how to make predictions with the trained model. 

### 99_fasttext_clust_EDA.Rmd
### 99_json_parse_upload.Rmd
### 99_logit_regression_classifier.Rmd
### 99_read_tweets_json.Rmd
### 99_tweet_object.Rmd




